// This file is generated by the configureFilesWithGitVersion.cmake script.
// It contains the current version number of a git repository.

#include <string>

namespace b
{
	inline const std::string& getPackageVersion()
	{
		static std::string version = "0.0.1.9-4f21";
		return version;
	}
}
