MyCppCodeBase: CppCodeBaseJenkinsjob.setup Namespace Reference
CppCodeBaseJenkinsjob.setup Namespace Reference
Functions
def main (config_file)
def get_job_name (job_base_name)
def configure_job_config_file (xml_file_path, job_name, build_repository_address, jenkinsjob_repository_address)
Detailed Description
This script runs the CppCodeBaseMachines setupdDockerContainer.py script,
but adds additional CppCodeBaseJenkinsjob jobs.
The script takes a .json config file for the machine setup, which can
contain an additional dictionary for defineing CppCodeBase jobs.
{
  ...
  "CppCodeBaseJobs" : {
"MyCppCodeBaseJob" : "ssh://me@repository_machine:/share/MyRepo.git"
  },
  ...
}
Function Documentation
configure_job_config_file()
def CppCodeBaseJenkinsjob.setup.configure_job_config_file (xml_file_path, job_name, build_repository_address, jenkinsjob_repository_address)
Fills in the blanks in the config file and copies it to the given job
directory.
References CppCodeBaseJenkinsjob.setup.main().
Referenced by CppCodeBaseJenkinsjob.setup.main().
get_job_name()
def CppCodeBaseJenkinsjob.setup.get_job_name (job_base_name)
Add the version to the base name.
Referenced by CppCodeBaseJenkinsjob.setup.main().
main()
def CppCodeBaseJenkinsjob.setup.main (config_file)
References CppCodeBaseJenkinsjob.setup.configure_job_config_file(), and CppCodeBaseJenkinsjob.setup.get_job_name().
Referenced by CppCodeBaseJenkinsjob.setup.configure_job_config_file().