MyCPFProject: CPFMachines.config_data_tests.TestConfigData Class Reference
CPFMachines.config_data_tests.TestConfigData Class Reference
Public Member Functions
def test_reading_the_config_file_works (self)
def test_get_host_machine_connection (self)
def test_get_container_machine_dictionary (self)
def test_validation_checks_version (self)
def test_validation_checks_one_linux_machine_available (self)
def test_validation_checks_container_use_linux_machines (self)
def test_validation_checks_that_all_hosts_are_in_use (self)
def test_validation_checks_that_host_ids_are_unique (self)
def test_validation_checks_that_host_accounts_are_unique (self)
def test_validation_checks_that_slave_executors_number (self)
def test_validation_checks_that_container_hosts_have_temp_dir (self)
Detailed Description
Fixture class for testing the FakeFileSystemAccess class.
Member Function Documentation
test_get_container_machine_dictionary()
def CPFMachines.config_data_tests.TestConfigData.test_get_container_machine_dictionary (self)
Verify the output is correct.
References CPFMachines.config_data.get_example_config_dict().
test_get_host_machine_connection()
def CPFMachines.config_data_tests.TestConfigData.test_get_host_machine_connection (self)
References CPFMachines.config_data.get_example_config_dict().
test_reading_the_config_file_works()
def CPFMachines.config_data_tests.TestConfigData.test_reading_the_config_file_works (self)
Happy case test for reading a config file.
References CPFMachines.config_data.get_example_config_dict().
test_validation_checks_container_use_linux_machines()
def CPFMachines.config_data_tests.TestConfigData.test_validation_checks_container_use_linux_machines (self)
The jenkins-master and web-server must be assigned to a Linux host machine.
References CPFMachines.config_data.get_example_config_dict().
test_validation_checks_one_linux_machine_available()
def CPFMachines.config_data_tests.TestConfigData.test_validation_checks_one_linux_machine_available (self)
The jenkins master and web-server require a linux machine, so at least one must be available.
References CPFMachines.config_data.get_example_config_dict().
test_validation_checks_that_all_hosts_are_in_use()
def CPFMachines.config_data_tests.TestConfigData.test_validation_checks_that_all_hosts_are_in_use (self)
If a host is not referenced, it is probably an error in the config file.
References CPFMachines.config_data.get_example_config_dict().
test_validation_checks_that_container_hosts_have_temp_dir()
def CPFMachines.config_data_tests.TestConfigData.test_validation_checks_that_container_hosts_have_temp_dir (self)
We need a temporary directory for the build-context when building
docker container.
References CPFMachines.config_data.get_example_config_dict().
test_validation_checks_that_host_accounts_are_unique()
def CPFMachines.config_data_tests.TestConfigData.test_validation_checks_that_host_accounts_are_unique (self)
It is probably an error in the config file if an account gets used more than once.
References CPFMachines.config_data.get_example_config_dict().
test_validation_checks_that_host_ids_are_unique()
def CPFMachines.config_data_tests.TestConfigData.test_validation_checks_that_host_ids_are_unique (self)
The code requires that host ids to be unique.
References CPFMachines.config_data.get_example_config_dict().
test_validation_checks_that_slave_executors_number()
def CPFMachines.config_data_tests.TestConfigData.test_validation_checks_that_slave_executors_number (self)
Zero or less executors in a jenkins slave makes no sense.
References CPFMachines.config_data.get_example_config_dict().
test_validation_checks_version()
def CPFMachines.config_data_tests.TestConfigData.test_validation_checks_version (self)
For now, the version in the file must exactly fit the version of the reading library.
References CPFMachines.config_data.get_example_config_dict().