// This file is generated by CPFCMake.
// It contains the version number of the package .

#include <string>

namespace a
{
	inline const std::string& getPackageVersion()
	{
		static std::string version = "2.0.3.25-ba66";
		return version;
	}
}
