MyCppCodeBase: cppcodebasebuildscripts.miscosaccess.MiscOsAccess Class Reference
cppcodebasebuildscripts.miscosaccess.MiscOsAccess Class Reference
Public Member Functions
def execute_command (self, command)
def execute_commands_in_parallel (self, commands, cwd=None, printOutput=True)
def print_console (self, string)
def chdir (self, path)
def system (self)
def cpu_count (self)
Detailed Description
Wraps some miscellaneous functions that access the functionality of the operating system.
This allows replacing the calls to these functions in tests.
Member Function Documentation
chdir()
def cppcodebasebuildscripts.miscosaccess.MiscOsAccess.chdir (self, path)
Change the current directory
cpu_count()
def cppcodebasebuildscripts.miscosaccess.MiscOsAccess.cpu_count (self)
execute_command()
def cppcodebasebuildscripts.miscosaccess.MiscOsAccess.execute_command (self, command)
Executes the command and prints the result. Returns true if the errorcode was 0.
Use this version when you do not need the output string and only run one command
in parallel.
References cppcodebasebuildscripts.miscosaccess.MiscOsAccess._get_printed_command().
execute_commands_in_parallel()
def cppcodebasebuildscripts.miscosaccess.MiscOsAccess.execute_commands_in_parallel (self, commands, cwd = None, printOutput = True)
Executes multiple command-line commands in parallel.
The commands should be given in one string, like it would be typed into the command line.
The return code, standard output and error output can be retrieved from the returned list of dictionaries.
References cppcodebasebuildscripts.miscosaccess.MiscOsAccess._get_printed_command().
print_console()
def cppcodebasebuildscripts.miscosaccess.MiscOsAccess.print_console (self, string)
Referenced by cppcodebasebuildscripts.miscosaccess.FakeMiscOsAccess.chdir(), cppcodebasebuildscripts.miscosaccess.FakeMiscOsAccess.execute_command(), and cppcodebasebuildscripts.miscosaccess.FakeMiscOsAccess.execute_commands_in_parallel().
system()
def cppcodebasebuildscripts.miscosaccess.MiscOsAccess.system (self)
Return the name of the platform (Linux or Windows in our case)