CMakeProjectFramework: CPFMachines.config_data Namespace Reference
CPFMachines.config_data Namespace Reference
Classes
class ConfigData
class ConfigItem
class ContainerConfig
class CPFJobConfig
class HostMachineInfo
class HTTPSRepositoryHostConfig
class JenkinsConfig
class JenkinsMasterHostConfig
class JenkinsSlaveConfig
class SSHRepositoryHostConfig
class WebserverConfig
Functions
def write_example_config_file (file_path)
def read_json_file (config_file)
def get_example_config_dict ()
def write_json_file (config_dict, file_path)
def get_checked_value (dictionary, key)
Variables
string KEY_VERSION = 'CPFMachinesVersion'
string KEY_LOGIN_DATA = 'HostMachines'
string KEY_MACHINE_ID = 'MachineID'
string KEY_HOST = 'HostNameOrIP'
string KEY_USER = 'User'
string KEY_PASSWORD = 'Password'
string KEY_OSTYPE = 'OSType'
string KEY_TEMPDIR = 'TemporaryDirectory'
string KEY_JENKINS_MASTER_HOST = 'JenkinsMasterHost'
string KEY_HOST_JENKINS_MASTER_SHARE = 'HostJenkinsMasterShare'
string KEY_SSH_REPOSITORY_HOSTS = 'SSHRepositoryHosts'
string KEY_SSH_DIR = 'SSHDir'
string KEY_HTTPS_REPOSITORY_HOSTS = 'HTTPSRepositoryHosts'
string KEY_JENKINS_SLAVES = 'JenkinsSlaves'
string KEY_EXECUTORS = "Executors"
string KEY_CONTAINER_NAME = "ContainerName"
string KEY_JENKINS_CONFIG = 'JenkinsConfig'
string KEY_USE_UNCONFIGURED_JENKINS = 'UseUnconfiguredJenkins'
string KEY_JENKINS_ADMIN_USER = 'JenkinsAdminUser'
string KEY_JENKINS_ADMIN_USER_PASSWORD = 'JenkinsAdminUserPassword'
string KEY_JENKINS_ACCOUNT_CONFIG_FILES = 'JenkinsAccountConfigFiles'
string KEY_JENKINS_JOB_CONFIG_FILES = 'JenkinsJobConfigFiles'
string KEY_JENKINS_APPROVED_SYSTEM_COMMANDS = 'JenkinsApprovedSystemCommands'
string KEY_JENKINS_APPROVED_SCRIPT_SIGNATURES = 'JenkinsApprovedScriptSignatures'
string KEY_CPF_JOBS = 'CPFJobs'
string KEY_JENKINSJOB_BASE_NAME = 'JenkinsJobBasename'
string KEY_REPOSITORY = 'Repository'
string KEY_WEBSERVER_CONFIG = 'WebServerConfig'
string KEY_HOST_HTML_SHARE = 'HostHTMLShare'
JENKINS_HOME_JENKINS_MASTER_CONTAINER = PurePosixPath('/var/jenkins_home')
Detailed Description
This module defines the structure of the config file that is used by the setup script.
It also offers utilities create empty config files and read the contents of the file into
python classes.
\TODO insert doxygen documentation here. How can we comment the example file without duplication?
Can we add comments to the KEY definitions that are visible in the docs?
Function Documentation
get_checked_value()
def CPFMachines.config_data.get_checked_value (dictionary, key)
Checks that the given key exists in the dictionary and that
it has a non empty value.
Referenced by CPFMachines.config_data.ConfigData.get_host_info().
get_example_config_dict()
def CPFMachines.config_data.get_example_config_dict ()
Returns a dictionary that contains the data of a valid example configuration.
Referenced by CPFMachines.hook_config_tests.TestHookConfig.test_reading_the_config_file_works(), CPFMachines.config_data_tests.TestConfigData.test_reading_the_config_file_works(), CPFMachines.config_data_tests.TestConfigData.test_validation_checks_container_use_linux_machines(), CPFMachines.config_data_tests.TestConfigData.test_validation_checks_one_linux_machine_available(), CPFMachines.config_data_tests.TestConfigData.test_validation_checks_that_all_hosts_are_in_use(), CPFMachines.config_data_tests.TestConfigData.test_validation_checks_that_container_hosts_have_temp_dir(), CPFMachines.config_data_tests.TestConfigData.test_validation_checks_that_host_accounts_are_unique(), CPFMachines.config_data_tests.TestConfigData.test_validation_checks_that_host_ids_are_unique(), CPFMachines.config_data_tests.TestConfigData.test_validation_checks_that_slave_executors_number(), CPFMachines.config_data_tests.TestConfigData.test_validation_checks_version(), and CPFMachines.config_data.write_example_config_file().
read_json_file()
def CPFMachines.config_data.read_json_file (config_file)
Returns the content of a json file as dictionary.
write_example_config_file()
def CPFMachines.config_data.write_example_config_file (file_path)
This function creates a small CPFMachines config file for documentation purposes.
References CPFMachines.config_data.get_example_config_dict(), and CPFMachines.config_data.write_json_file().
write_json_file()
def CPFMachines.config_data.write_json_file (config_dict, file_path)
Writes a dictionary to .json file.
Referenced by CPFMachines.config_data.write_example_config_file().
Variable Documentation
JENKINS_HOME_JENKINS_MASTER_CONTAINER
CPFMachines.config_data.JENKINS_HOME_JENKINS_MASTER_CONTAINER = PurePosixPath('/var/jenkins_home')
KEY_CONTAINER_NAME
string CPFMachines.config_data.KEY_CONTAINER_NAME = "ContainerName"
KEY_CPF_JOBS
string CPFMachines.config_data.KEY_CPF_JOBS = 'CPFJobs'
KEY_EXECUTORS
string CPFMachines.config_data.KEY_EXECUTORS = "Executors"
KEY_HOST
string CPFMachines.config_data.KEY_HOST = 'HostNameOrIP'
KEY_HOST_HTML_SHARE
string CPFMachines.config_data.KEY_HOST_HTML_SHARE = 'HostHTMLShare'
KEY_HOST_JENKINS_MASTER_SHARE
string CPFMachines.config_data.KEY_HOST_JENKINS_MASTER_SHARE = 'HostJenkinsMasterShare'
KEY_HTTPS_REPOSITORY_HOSTS
string CPFMachines.config_data.KEY_HTTPS_REPOSITORY_HOSTS = 'HTTPSRepositoryHosts'
KEY_JENKINS_ACCOUNT_CONFIG_FILES
string CPFMachines.config_data.KEY_JENKINS_ACCOUNT_CONFIG_FILES = 'JenkinsAccountConfigFiles'
KEY_JENKINS_ADMIN_USER
string CPFMachines.config_data.KEY_JENKINS_ADMIN_USER = 'JenkinsAdminUser'
KEY_JENKINS_ADMIN_USER_PASSWORD
string CPFMachines.config_data.KEY_JENKINS_ADMIN_USER_PASSWORD = 'JenkinsAdminUserPassword'
KEY_JENKINS_APPROVED_SCRIPT_SIGNATURES
string CPFMachines.config_data.KEY_JENKINS_APPROVED_SCRIPT_SIGNATURES = 'JenkinsApprovedScriptSignatures'
KEY_JENKINS_APPROVED_SYSTEM_COMMANDS
string CPFMachines.config_data.KEY_JENKINS_APPROVED_SYSTEM_COMMANDS = 'JenkinsApprovedSystemCommands'
KEY_JENKINS_CONFIG
string CPFMachines.config_data.KEY_JENKINS_CONFIG = 'JenkinsConfig'
KEY_JENKINS_JOB_CONFIG_FILES
string CPFMachines.config_data.KEY_JENKINS_JOB_CONFIG_FILES = 'JenkinsJobConfigFiles'
KEY_JENKINS_MASTER_HOST
string CPFMachines.config_data.KEY_JENKINS_MASTER_HOST = 'JenkinsMasterHost'
KEY_JENKINS_SLAVES
string CPFMachines.config_data.KEY_JENKINS_SLAVES = 'JenkinsSlaves'
KEY_JENKINSJOB_BASE_NAME
string CPFMachines.config_data.KEY_JENKINSJOB_BASE_NAME = 'JenkinsJobBasename'
KEY_LOGIN_DATA
string CPFMachines.config_data.KEY_LOGIN_DATA = 'HostMachines'
KEY_MACHINE_ID
string CPFMachines.config_data.KEY_MACHINE_ID = 'MachineID'
KEY_OSTYPE
string CPFMachines.config_data.KEY_OSTYPE = 'OSType'
KEY_PASSWORD
string CPFMachines.config_data.KEY_PASSWORD = 'Password'
KEY_REPOSITORY
string CPFMachines.config_data.KEY_REPOSITORY = 'Repository'
KEY_SSH_DIR
string CPFMachines.config_data.KEY_SSH_DIR = 'SSHDir'
KEY_SSH_REPOSITORY_HOSTS
string CPFMachines.config_data.KEY_SSH_REPOSITORY_HOSTS = 'SSHRepositoryHosts'
KEY_TEMPDIR
string CPFMachines.config_data.KEY_TEMPDIR = 'TemporaryDirectory'
KEY_USE_UNCONFIGURED_JENKINS
string CPFMachines.config_data.KEY_USE_UNCONFIGURED_JENKINS = 'UseUnconfiguredJenkins'
KEY_USER
string CPFMachines.config_data.KEY_USER = 'User'
KEY_VERSION
string CPFMachines.config_data.KEY_VERSION = 'CPFMachinesVersion'
KEY_WEBSERVER_CONFIG
string CPFMachines.config_data.KEY_WEBSERVER_CONFIG = 'WebServerConfig'