// This file is generated by the configureFilesWithGitVersion.cmake script.
// It contains the current version number of a git repository.

#include <string>

namespace a
{
	inline const std::string& getPackageVersion()
	{
		static std::string version = "2.0.3.21-e816";
		return version;
	}
}
