// This file is generated by CPFCMake.
// It contains the version number of the package .

#include <string>

namespace b
{
	inline const std::string& getPackageVersion()
	{
		static std::string version = "0.0.1.25-8e3f";
		return version;
	}
}
