// This file is generated by CPFCMake.
// It contains the version number of the package .

#include <string>

namespace g
{
	inline const std::string& getPackageVersion()
	{
		static std::string version = "0.0.0.33-9490";
		return version;
	}
}
