MyCppCodeBase: CppCodeBaseMachines.config_data Namespace Reference
CppCodeBaseMachines.config_data Namespace Reference
Classes
class ConfigData
class ContainerConfig
class CppCodeBaseJobConfig
class HostMachineConnection
class JenkinsAccountConfig
class JenkinsConfig
class JenkinsJobConfig
class JenkinsMasterHostConfig
class JenkinsSlaveConfig
class RepositoryHostConfig
class WebserverHostConfig
Functions
def write_example_config_file (file_path)
def read_json_file (config_file)
def get_example_config_dict ()
Variables
string KEY_VERSION = 'CppCodeBaseMachinesVersion'
string KEY_LOGIN_DATA = 'HostMachines'
string KEY_MACHINE_ID = 'MachineID'
string KEY_MACHINE_NAME = 'HostNameOrIP'
string KEY_USER = 'User'
string KEY_PASSWORD = 'Password'
string KEY_OSTYPE = 'OSType'
string KEY_TEMPDIR = 'TemporaryDirectory'
string KEY_JENKINS_MASTER_HOST = 'JenkinsMasterHost'
string KEY_HOST_JENKINS_MASTER_SHARE = 'HostJenkinsMasterShare'
string KEY_WEB_SERVER_HOST = 'WebServerHost'
string KEY_HOST_HTML_SHARE = 'HostHTMLShare'
string KEY_REPOSITORY_HOST = 'RepositoryHost'
string KEY_SSH_DIR = 'SSHDir'
string KEY_JENKINS_SLAVES = 'JenkinsSlaves'
string KEY_EXECUTORS = "Executors"
string KEY_CONTAINER_NAME = "ContainerName"
string KEY_JENKINS_CONFIG = 'JenkinsConfig'
string KEY_USE_UNCONFIGURED_JENKINS = 'UseUnconfiguredJenkins'
string KEY_JENKINS_ADMIN_USER = 'JenkinsAdminUser'
string KEY_JENKINS_ADMIN_USER_PASSWORD = 'JenkinsAdminUserPassword'
string KEY_JENKINS_ACCOUNT_CONFIG_FILES = 'JenkinsAccountConfigFiles'
string KEY_JENKINS_JOB_CONFIG_FILES = 'JenkinsJobConfigFiles'
string KEY_CPP_CODE_BASE_JOBS = 'CppCodeBaseJobs'
string KEY_JENKINS_APPROVED_SYSTEM_COMMANDS = 'JenkinsApprovedSystemCommands'
string KEY_JENKINS_APPROVED_SCRIPT_SIGNATURES = 'JenkinsApprovedScriptSignatures'
Detailed Description
This module defines the structure of the config file that is used by the setup script.
It also offers utilities create empty config files and read the contents of the file into
python classes.
\TODO insert doxygen documentation here. How can we comment the example file without duplication?
Can we add comments to the KEY definitions that are visible in the docs?
Function Documentation
get_example_config_dict()
def CppCodeBaseMachines.config_data.get_example_config_dict ()
Returns a dictionary that contains the data of a valid example configuration.
Referenced by CppCodeBaseMachines.config_data_tests.TestConfigData.test_get_container_machine_dictionary(), CppCodeBaseMachines.config_data_tests.TestConfigData.test_get_host_machine_connection(), CppCodeBaseMachines.config_data_tests.TestConfigData.test_reading_the_config_file_works(), CppCodeBaseMachines.config_data_tests.TestConfigData.test_validation_checks_container_use_linux_machines(), CppCodeBaseMachines.config_data_tests.TestConfigData.test_validation_checks_one_linux_machine_available(), CppCodeBaseMachines.config_data_tests.TestConfigData.test_validation_checks_that_all_hosts_are_in_use(), CppCodeBaseMachines.config_data_tests.TestConfigData.test_validation_checks_that_container_hosts_have_temp_dir(), CppCodeBaseMachines.config_data_tests.TestConfigData.test_validation_checks_that_host_accounts_are_unique(), CppCodeBaseMachines.config_data_tests.TestConfigData.test_validation_checks_that_host_ids_are_unique(), CppCodeBaseMachines.config_data_tests.TestConfigData.test_validation_checks_that_slave_executors_number(), CppCodeBaseMachines.config_data_tests.TestConfigData.test_validation_checks_version(), and CppCodeBaseMachines.config_data.write_example_config_file().
read_json_file()
def CppCodeBaseMachines.config_data.read_json_file (config_file)
Returns the content of a json file as dictionary.
write_example_config_file()
def CppCodeBaseMachines.config_data.write_example_config_file (file_path)
This function creates a small CppCodeBaseMachines config file for documentation purposes.
References CppCodeBaseMachines.config_data.get_example_config_dict().
Variable Documentation
KEY_CONTAINER_NAME
string CppCodeBaseMachines.config_data.KEY_CONTAINER_NAME = "ContainerName"
KEY_CPP_CODE_BASE_JOBS
string CppCodeBaseMachines.config_data.KEY_CPP_CODE_BASE_JOBS = 'CppCodeBaseJobs'
KEY_EXECUTORS
string CppCodeBaseMachines.config_data.KEY_EXECUTORS = "Executors"
KEY_HOST_HTML_SHARE
string CppCodeBaseMachines.config_data.KEY_HOST_HTML_SHARE = 'HostHTMLShare'
KEY_HOST_JENKINS_MASTER_SHARE
string CppCodeBaseMachines.config_data.KEY_HOST_JENKINS_MASTER_SHARE = 'HostJenkinsMasterShare'
KEY_JENKINS_ACCOUNT_CONFIG_FILES
string CppCodeBaseMachines.config_data.KEY_JENKINS_ACCOUNT_CONFIG_FILES = 'JenkinsAccountConfigFiles'
KEY_JENKINS_ADMIN_USER
string CppCodeBaseMachines.config_data.KEY_JENKINS_ADMIN_USER = 'JenkinsAdminUser'
KEY_JENKINS_ADMIN_USER_PASSWORD
string CppCodeBaseMachines.config_data.KEY_JENKINS_ADMIN_USER_PASSWORD = 'JenkinsAdminUserPassword'
KEY_JENKINS_APPROVED_SCRIPT_SIGNATURES
string CppCodeBaseMachines.config_data.KEY_JENKINS_APPROVED_SCRIPT_SIGNATURES = 'JenkinsApprovedScriptSignatures'
KEY_JENKINS_APPROVED_SYSTEM_COMMANDS
string CppCodeBaseMachines.config_data.KEY_JENKINS_APPROVED_SYSTEM_COMMANDS = 'JenkinsApprovedSystemCommands'
KEY_JENKINS_CONFIG
string CppCodeBaseMachines.config_data.KEY_JENKINS_CONFIG = 'JenkinsConfig'
KEY_JENKINS_JOB_CONFIG_FILES
string CppCodeBaseMachines.config_data.KEY_JENKINS_JOB_CONFIG_FILES = 'JenkinsJobConfigFiles'
KEY_JENKINS_MASTER_HOST
string CppCodeBaseMachines.config_data.KEY_JENKINS_MASTER_HOST = 'JenkinsMasterHost'
KEY_JENKINS_SLAVES
string CppCodeBaseMachines.config_data.KEY_JENKINS_SLAVES = 'JenkinsSlaves'
KEY_LOGIN_DATA
string CppCodeBaseMachines.config_data.KEY_LOGIN_DATA = 'HostMachines'
KEY_MACHINE_ID
string CppCodeBaseMachines.config_data.KEY_MACHINE_ID = 'MachineID'
KEY_MACHINE_NAME
string CppCodeBaseMachines.config_data.KEY_MACHINE_NAME = 'HostNameOrIP'
KEY_OSTYPE
string CppCodeBaseMachines.config_data.KEY_OSTYPE = 'OSType'
KEY_PASSWORD
string CppCodeBaseMachines.config_data.KEY_PASSWORD = 'Password'
KEY_REPOSITORY_HOST
string CppCodeBaseMachines.config_data.KEY_REPOSITORY_HOST = 'RepositoryHost'
KEY_SSH_DIR
string CppCodeBaseMachines.config_data.KEY_SSH_DIR = 'SSHDir'
KEY_TEMPDIR
string CppCodeBaseMachines.config_data.KEY_TEMPDIR = 'TemporaryDirectory'
KEY_USE_UNCONFIGURED_JENKINS
string CppCodeBaseMachines.config_data.KEY_USE_UNCONFIGURED_JENKINS = 'UseUnconfiguredJenkins'
KEY_USER
string CppCodeBaseMachines.config_data.KEY_USER = 'User'
KEY_VERSION
string CppCodeBaseMachines.config_data.KEY_VERSION = 'CppCodeBaseMachinesVersion'
KEY_WEB_SERVER_HOST
string CppCodeBaseMachines.config_data.KEY_WEB_SERVER_HOST = 'WebServerHost'