CMakeProjectFramework: CPFTests.simpleonelibcpftestproject_tests.SimpleOneLibCPFTestProjectFixture Class Reference
CPFTests.simpleonelibcpftestproject_tests.SimpleOneLibCPFTestProjectFixture Class Reference
Public Member Functions
def setUp (self)
def test_configure_script (self)
def test_target_existence (self)
def test_opencppcoverage_target_works (self)
Public Member Functions inherited from CPFTests.testprojectfixture.TestProjectFixture
def setUp (self)
def replace_package_in_test_project_with_local (self, package)
def run_python_command (self, argument, print_output=miscosaccess.OutputMode.ON_ERROR, print_command=False)
def is_visual_studio_config (self)
def is_linux_debug_config (self)
def is_clang_config (self)
def is_make_config (self)
def is_ninja_config (self)
def is_make_config (self)
def is_msvc_or_debug_config (self)
def assert_targets_build (self, targets)
def build_target (self, target, config=None)
def assert_targets_do_not_exist (self, targets)
def generate_project (self)
Public Attributes
project
repository
Public Attributes inherited from CPFTests.testprojectfixture.TestProjectFixture
fsa
osa
test_dir
Detailed Description
A fixture for tests that can be done with a minimal project that has no test executable and
only a library package.
Member Function Documentation
setUp()
def CPFTests.simpleonelibcpftestproject_tests.SimpleOneLibCPFTestProjectFixture.setUp (self)
test_configure_script()
def CPFTests.simpleonelibcpftestproject_tests.SimpleOneLibCPFTestProjectFixture.test_configure_script (self)
This tests the underlying functionality of the '1_Configure.py' script.
References CPFTests.testprojectfixture.TestProjectFixture.osa, CPFTests.testprojectfixture.TestProjectFixture.run_python_command(), and CPFTests.testprojectfixture.TestProjectFixture.test_dir.
test_opencppcoverage_target_works()
def CPFTests.simpleonelibcpftestproject_tests.SimpleOneLibCPFTestProjectFixture.test_opencppcoverage_target_works (self)
Check that the target runs the OpenCppCoverage.exe for the
compiler debug config and not for the release config.
References CPFTests.testprojectfixture.TestProjectFixture.build_target(), CPFTests.testprojectfixture.TestProjectFixture.generate_project(), and CPFTests.testprojectfixture.TestProjectFixture.is_visual_studio_config().
test_target_existence()
def CPFTests.simpleonelibcpftestproject_tests.SimpleOneLibCPFTestProjectFixture.test_target_existence (self)
Check that the pipeline target builds.
References CPFTests.testprojectfixture.TestProjectFixture.assert_targets_build(), CPFTests.testprojectfixture.TestProjectFixture.assert_targets_do_not_exist(), CPFTests.testprojectfixture.TestProjectFixture.generate_project(), CPFTests.testprojectfixture.TestProjectFixture.is_clang_config(), CPFTests.testprojectfixture.TestProjectFixture.is_linux_debug_config(), CPFTests.testprojectfixture.TestProjectFixture.is_msvc_or_debug_config(), and CPFTests.testprojectfixture.TestProjectFixture.is_visual_studio_config().
Member Data Documentation
project
CPFTests.simpleonelibcpftestproject_tests.SimpleOneLibCPFTestProjectFixture.project
Referenced by CPFTests.testprojectfixture.TestProjectFixture.setUp().
repository
CPFTests.simpleonelibcpftestproject_tests.SimpleOneLibCPFTestProjectFixture.repository