MyCppCodeBase: CppCodeBaseMachines.setup Namespace Reference
CppCodeBaseMachines.setup Namespace Reference
Functions
def configure_file (source_file, dest_file, replacement_dictionary)
def main (config_file)
def dev_message (text)
def rtocontainercopy (source_host_connection, target_host_connection, container_conf, source_file, target_file)
Function Documentation
configure_file()
def CppCodeBaseMachines.setup.configure_file (source_file, dest_file, replacement_dictionary)
Searches in source_file for the keys in replacement_dictionary, replaces them
with the values and writes the result to dest_file.
Referenced by CppCodeBaseMachines.setup.rtocontainercopy().
dev_message()
def CppCodeBaseMachines.setup.dev_message (text)
Print function emphasizes the printed string with some dashes.
It is intended to be used for debugging during development.
References CppCodeBaseMachines.setup.rtocontainercopy().
main()
def CppCodeBaseMachines.setup.main (config_file)
Entry point of the scrpit.
Referenced by CppCodeBaseMachines.setup.rtocontainercopy().
rtocontainercopy()
def CppCodeBaseMachines.setup.rtocontainercopy (source_host_connection, target_host_connection, container_conf, source_file, target_file)
Copies the source_file from a host machine to the target target path target_file on a container.
References CppCodeBaseMachines.setup.configure_file(), and CppCodeBaseMachines.setup.main().
Referenced by CppCodeBaseMachines.setup.dev_message().