// This file is generated by CPFCMake.
// It contains the version number of the package .

#include <string>

namespace mylib
{
	inline const std::string& getPackageVersion()
	{
		static std::string version = "0.0.7.4-9041";
		return version;
	}
}
