
#ifndef LIBAPACKAGE_FIXTURES_EXPORT_H
#define LIBAPACKAGE_FIXTURES_EXPORT_H

#ifdef LIBAPACKAGE_FIXTURES_STATIC_DEFINE
#  define LIBAPACKAGE_FIXTURES_EXPORT
#  define LIBAPACKAGE_FIXTURES_NO_EXPORT
#else
#  ifndef LIBAPACKAGE_FIXTURES_EXPORT
#    ifdef libAPackage_fixtures_EXPORTS
        /* We are building this library */
#      define LIBAPACKAGE_FIXTURES_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define LIBAPACKAGE_FIXTURES_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef LIBAPACKAGE_FIXTURES_NO_EXPORT
#    define LIBAPACKAGE_FIXTURES_NO_EXPORT 
#  endif
#endif

#ifndef LIBAPACKAGE_FIXTURES_DEPRECATED
#  define LIBAPACKAGE_FIXTURES_DEPRECATED __declspec(deprecated)
#endif

#ifndef LIBAPACKAGE_FIXTURES_DEPRECATED_EXPORT
#  define LIBAPACKAGE_FIXTURES_DEPRECATED_EXPORT LIBAPACKAGE_FIXTURES_EXPORT LIBAPACKAGE_FIXTURES_DEPRECATED
#endif

#ifndef LIBAPACKAGE_FIXTURES_DEPRECATED_NO_EXPORT
#  define LIBAPACKAGE_FIXTURES_DEPRECATED_NO_EXPORT LIBAPACKAGE_FIXTURES_NO_EXPORT LIBAPACKAGE_FIXTURES_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef LIBAPACKAGE_FIXTURES_NO_DEPRECATED
#    define LIBAPACKAGE_FIXTURES_NO_DEPRECATED
#  endif
#endif

#endif /* LIBAPACKAGE_FIXTURES_EXPORT_H */
