// This file is generated by CPFCMake.
// It contains the version number of the package .

#include <string>

namespace CCPFTestPackage
{
	inline const std::string& getPackageVersion()
	{
		static std::string version = "0.0.0.92-3cd3";
		return version;
	}
}
