// This file is generated by CPFCMake.
// It contains the version number of the package .

#include <string>

namespace e
{
	inline const std::string& getPackageVersion()
	{
		static std::string version = "0.0.0.34-aba1";
		return version;
	}
}
