// This file is generated by the configureFilesWithGitVersion.cmake script.
// It contains the current version number of a git repository.

#include <string>

namespace f
{
	inline const std::string& getPackageVersion()
	{
		static std::string version = "0.0.1.11-3995";
		return version;
	}
}
