CMakeProjectFramework: python.miscosaccess.MiscOsAccess Class Reference
python.miscosaccess.MiscOsAccess Class Reference
Public Member Functions
def execute_command (self, command, cwd=None)
def execute_command_output (self, command, cwd=None, print_output=OutputMode.ALWAYS, print_command=False)
def execute_commands_in_parallel (self, commands, cwd=None, printOutput=True)
def print_console (self, string)
def chdir (self, path)
def system (self)
def cpu_count (self)
Detailed Description
Wraps some miscellaneous functions that access the functionality of the operating system.
This allows replacing the calls to these functions in tests.
Member Function Documentation
chdir()
def python.miscosaccess.MiscOsAccess.chdir (self, path)
Change the current directory
cpu_count()
def python.miscosaccess.MiscOsAccess.cpu_count (self)
execute_command()
def python.miscosaccess.MiscOsAccess.execute_command (self, command, cwd = None)
Executes the command and prints the result. Returns true if the errorcode was 0.
Use this version when you do not need the output string and only run one command
in parallel.
References python.miscosaccess.MiscOsAccess.execute_command_output().
execute_command_output()
def python.miscosaccess.MiscOsAccess.execute_command_output (self, command, cwd = None, print_output = OutputMode.ALWAYS, print_command = False)
Executes the given command and returns a list with that contains the output lines of the process.
The function will print output as soon as it is created when setting the print_output option.
Note that when your command runs a python script, you have to add the python -u option to make
sure the output is displayed immediately.
The function throws a CalledProcessError when the command fails.
The function currently only uses utf-8 encoded output strings. Other variants caused errors
when calling python scripts that also call this function.
References python.miscosaccess.MiscOsAccess._get_printed_command().
Referenced by python.miscosaccess.MiscOsAccess.execute_command().
execute_commands_in_parallel()
def python.miscosaccess.MiscOsAccess.execute_commands_in_parallel (self, commands, cwd = None, printOutput = True)
Executes multiple command-line commands in parallel.
The commands should be given in one string, like it would be typed into the command line.
The return code, standard output and error output can be retrieved from the returned list of dictionaries.
References python.miscosaccess.MiscOsAccess._get_printed_command().
print_console()
def python.miscosaccess.MiscOsAccess.print_console (self, string)
Referenced by python.miscosaccess.FakeMiscOsAccess.chdir(), python.miscosaccess.FakeMiscOsAccess.execute_command(), and python.miscosaccess.FakeMiscOsAccess.execute_commands_in_parallel().
system()
def python.miscosaccess.MiscOsAccess.system (self)
Return the name of the platform (Linux or Windows in our case)