MyCppCodeBase: cppcodebasebuildscripts.filesystemaccess.FileSystemAccess Class Reference
cppcodebasebuildscripts.filesystemaccess.FileSystemAccess Class Reference
Public Member Functions
def exists (self, path)
def isfile (self, path)
def isdir (self, path)
def mkdir (self, path)
def mkdirs (self, path)
def listdir (self, path)
def rmtree (self, path)
def copyfile (self, path_from, path_to)
Detailed Description
This class wraps the accesses to the file-system to
allow the usage of a fake file-system for tests.
Member Function Documentation
copyfile()
def cppcodebasebuildscripts.filesystemaccess.FileSystemAccess.copyfile (self, path_from, path_to)
Copies a file.
exists()
def cppcodebasebuildscripts.filesystemaccess.FileSystemAccess.exists (self, path)
Returns true if the path exists.
Referenced by cppcodebasebuildscripts.filesystemaccess.FakeFileSystemAccess.mkdir().
isdir()
def cppcodebasebuildscripts.filesystemaccess.FileSystemAccess.isdir (self, path)
Returns true if the path leads to a directory.
Referenced by cppcodebasebuildscripts.filesystemaccess.FakeFileSystemAccess.rmtree().
isfile()
def cppcodebasebuildscripts.filesystemaccess.FileSystemAccess.isfile (self, path)
Returns true if the path leads to a file.
listdir()
def cppcodebasebuildscripts.filesystemaccess.FileSystemAccess.listdir (self, path)
Returns all entries in the directory given by path except . and .. .
Throws when path does not exist?
mkdir()
def cppcodebasebuildscripts.filesystemaccess.FileSystemAccess.mkdir (self, path)
Creates a directory. The parent directory must exist.
mkdirs()
def cppcodebasebuildscripts.filesystemaccess.FileSystemAccess.mkdirs (self, path)
Creates multiple directories. This will not throw an error if a directory already exists.
Referenced by cppcodebasebuildscripts.filesystemaccess.FakeFileSystemAccess.mkdir().
rmtree()
def cppcodebasebuildscripts.filesystemaccess.FileSystemAccess.rmtree (self, path)
Removes a directory and all of its content.