CMakeProjectFramework: CPFMachines.setup Namespace Reference
CPFMachines.setup Namespace Reference
Classes
class MachinesController
Functions
def configure_file (source_file, dest_file, replacement_dictionary)
def main (config_file)
def dev_message (text)
def get_job_name (job_base_name)
Detailed Description
This script removes and adds and starts all docker container of the CMakeProjectFramework infrastructure.
Arguments:
1. - The path to a configuration json file.
(An empty file can be generated with the createEmptyconfig_files.py script)
\todo Setting up the windows slaves needs to be automated. Can we use a windows container technology that does not conflict with
the VMWare virtual machines?
Function Documentation
configure_file()
def CPFMachines.setup.configure_file (source_file, dest_file, replacement_dictionary)
Searches in source_file for the keys in replacement_dictionary, replaces them
with the values and writes the result to dest_file.
Referenced by CPFMachines.setup.MachinesController.configure_jenkins_master().
dev_message()
def CPFMachines.setup.dev_message (text)
Print function emphasizes the printed string with some dashes.
It is intended to be used for debugging during development.
get_job_name()
def CPFMachines.setup.get_job_name (job_base_name)
Add the version to the base name.
References CPFMachines.setup.main().
Referenced by CPFMachines.setup.MachinesController.configure_jenkins_master().
main()
def CPFMachines.setup.main (config_file)
Entry point of the script.
Referenced by CPFMachines.setup.get_job_name().