// This file is generated by CPFCMake.
// It contains the version number of the package .

#include <string>

namespace d
{
	inline const std::string& getPackageVersion()
	{
		static std::string version = "0.0.0.42-8439";
		return version;
	}
}
