CMakeProjectFramework: CPFMachines.dockerutil Namespace Reference
CPFMachines.dockerutil Namespace Reference
Functions
def container_exists (connection, container)
def get_all_docker_container (connection)
def container_is_running (connection, container)
def get_running_docker_container (connection)
def stop_docker_container (connection, container)
def start_docker_container (connection, container)
def remove_container (connection, container)
def docker_container_image_exists (connection, image_name)
def build_docker_image (connection, image_name, context_source_dir, docker_file, build_args, text_files, binary_files=[])
def docker_run_detached (host_connection, container_config, resolved_hosts=[])
def run_commands_in_container (host_connection, container_config, commands, user=None)
def run_command_in_container (connection, container_config, command, user=None, print_command=True, print_output=False)
def copy_textfile_to_container (connection, container_conf, source_path, target_path)
def copy_file_from_host_to_container (host_connection, container_conf, source_file, target_file)
def container_to_container_copy (source_host_connection, source_container_conf, target_host_connection, target_container_conf, source_file, target_file)
def copy_local_textfile_tree_to_container (local_source_dir, container_host_connection, container_config, container_target_dir)
def rtocontainercopy (source_host_connection, target_host_connection, container_conf, source_file, target_file)
def containertorcopy (source_host_connection, container_conf, target_host_connection, source_file, target_file)
Detailed Description
Contains functions for basic remote container operations.
Function Documentation
build_docker_image()
def CPFMachines.dockerutil.build_docker_image (connection, image_name, context_source_dir, docker_file, build_args, text_files, binary_files = [])
container_exists()
def CPFMachines.dockerutil.container_exists (connection, container)
Returns true if the container exists on the host.
References CPFMachines.dockerutil.get_all_docker_container().
container_is_running()
def CPFMachines.dockerutil.container_is_running (connection, container)
Returns true if the container is running on its host.
References CPFMachines.dockerutil.get_running_docker_container().
container_to_container_copy()
def CPFMachines.dockerutil.container_to_container_copy (source_host_connection, source_container_conf, target_host_connection, target_container_conf, source_file, target_file)
Copies a file from one container to another.
References CPFMachines.dockerutil.rtocontainercopy().
containertorcopy()
def CPFMachines.dockerutil.containertorcopy (source_host_connection, container_conf, target_host_connection, source_file, target_file)
Copies a file from a container to an ssh host.
copy_file_from_host_to_container()
def CPFMachines.dockerutil.copy_file_from_host_to_container (host_connection, container_conf, source_file, target_file)
References CPFMachines.dockerutil.run_command_in_container().
Referenced by CPFMachines.dockerutil.copy_textfile_to_container(), and CPFMachines.dockerutil.rtocontainercopy().
copy_local_textfile_tree_to_container()
def CPFMachines.dockerutil.copy_local_textfile_tree_to_container (local_source_dir, container_host_connection, container_config, container_target_dir)
Copy the contents of a local directory to a container directory.
References CPFMachines.dockerutil.copy_textfile_to_container().
copy_textfile_to_container()
def CPFMachines.dockerutil.copy_textfile_to_container (connection, container_conf, source_path, target_path)
We first copy the file to host_temp_dir and then to the container.
References CPFMachines.dockerutil.copy_file_from_host_to_container().
Referenced by CPFMachines.dockerutil.copy_local_textfile_tree_to_container().
docker_container_image_exists()
def CPFMachines.dockerutil.docker_container_image_exists (connection, image_name)
docker_run_detached()
def CPFMachines.dockerutil.docker_run_detached (host_connection, container_config, resolved_hosts = [])
Executes the docker run command for a container on a given container host.
resolved_hosts:     A list of hosts machine names that are accessed by the container.
                    This makes sure name resolution of these machines works within the container.
get_all_docker_container()
def CPFMachines.dockerutil.get_all_docker_container (connection)
Referenced by CPFMachines.dockerutil.container_exists().
get_running_docker_container()
def CPFMachines.dockerutil.get_running_docker_container (connection)
Referenced by CPFMachines.dockerutil.container_is_running().
remove_container()
def CPFMachines.dockerutil.remove_container (connection, container)
This removes a given docker container and will fail if the container is running.
rtocontainercopy()
def CPFMachines.dockerutil.rtocontainercopy (source_host_connection, target_host_connection, container_conf, source_file, target_file)
Copies the source_file from a host machine to the target target path target_file on a container.
References CPFMachines.dockerutil.copy_file_from_host_to_container().
Referenced by CPFMachines.dockerutil.container_to_container_copy().
run_command_in_container()
def CPFMachines.dockerutil.run_command_in_container (connection, container_config, command, user = None, print_command = True, print_output = False)
The user option can be used to run the command for a different user then
the containers default user.
Referenced by CPFMachines.dockerutil.copy_file_from_host_to_container(), and CPFMachines.dockerutil.run_commands_in_container().
run_commands_in_container()
def CPFMachines.dockerutil.run_commands_in_container (host_connection, container_config, commands, user = None)
References CPFMachines.dockerutil.run_command_in_container().
start_docker_container()
def CPFMachines.dockerutil.start_docker_container (connection, container)
stop_docker_container()
def CPFMachines.dockerutil.stop_docker_container (connection, container)