// This file is generated by the configureFilesWithGitVersion.cmake script.
// It contains the current version number of a git repository.

#include <string>

namespace c
{
	inline const std::string& getPackageVersion()
	{
		static std::string version = "1.1.6.38-c8b1";
		return version;
	}
}
