// This file is generated by the configureFilesWithGitVersion.cmake script.
// It contains the current version number of a git repository.

#include <string>

namespace g
{
	inline const std::string& getPackageVersion()
	{
		static std::string version = "0.0.0.29-6765";
		return version;
	}
}
