
#ifndef BPACKAGE_FIXTURES_EXPORT_H
#define BPACKAGE_FIXTURES_EXPORT_H

#ifdef BPACKAGE_FIXTURES_STATIC_DEFINE
#  define BPACKAGE_FIXTURES_EXPORT
#  define BPACKAGE_FIXTURES_NO_EXPORT
#else
#  ifndef BPACKAGE_FIXTURES_EXPORT
#    ifdef BPackage_fixtures_EXPORTS
        /* We are building this library */
#      define BPACKAGE_FIXTURES_EXPORT __declspec(dllexport)
#    else
        /* We are using this library */
#      define BPACKAGE_FIXTURES_EXPORT __declspec(dllimport)
#    endif
#  endif

#  ifndef BPACKAGE_FIXTURES_NO_EXPORT
#    define BPACKAGE_FIXTURES_NO_EXPORT 
#  endif
#endif

#ifndef BPACKAGE_FIXTURES_DEPRECATED
#  define BPACKAGE_FIXTURES_DEPRECATED __declspec(deprecated)
#endif

#ifndef BPACKAGE_FIXTURES_DEPRECATED_EXPORT
#  define BPACKAGE_FIXTURES_DEPRECATED_EXPORT BPACKAGE_FIXTURES_EXPORT BPACKAGE_FIXTURES_DEPRECATED
#endif

#ifndef BPACKAGE_FIXTURES_DEPRECATED_NO_EXPORT
#  define BPACKAGE_FIXTURES_DEPRECATED_NO_EXPORT BPACKAGE_FIXTURES_NO_EXPORT BPACKAGE_FIXTURES_DEPRECATED
#endif

#if 0 /* DEFINE_NO_DEPRECATED */
#  ifndef BPACKAGE_FIXTURES_NO_DEPRECATED
#    define BPACKAGE_FIXTURES_NO_DEPRECATED
#  endif
#endif

#endif /* BPACKAGE_FIXTURES_EXPORT_H */
