// This file is generated by CPFCMake.
// It contains the version number of the package .

#include <string>

namespace f
{
	inline const std::string& getPackageVersion()
	{
		static std::string version = "0.0.1.15-d077";
		return version;
	}
}
