MyCppCodeBase: cppcodebasebuildscripts.docopt Namespace Reference
cppcodebasebuildscripts.docopt Namespace Reference
Classes
class AnyOptions
class Argument
class ChildPattern
class Command
class Dict
class DocoptExit
class DocoptLanguageError
class Either
class OneOrMore
class Option
class Optional
class ParentPattern
class Pattern
class Required
class TokenStream
Functions
def parse_long (tokens, options)
def parse_shorts (tokens, options)
def parse_pattern (source, options)
def parse_expr (tokens, options)
def parse_seq (tokens, options)
def parse_atom (tokens, options)
def parse_argv (tokens, options, options_first=False)
def parse_defaults (doc)
def printable_usage (doc)
def formal_usage (printable_usage)
def extras (help, version, options, doc)
def docopt (doc, argv=None, help=True, version=None, options_first=False)
Detailed Description
Pythonic command-line interface parser that will make you smile.
 * http://docopt.org
 * Repository and issue-tracker: https://github.com/docopt/docopt
 * Licensed under terms of MIT license (see LICENSE-MIT)
 * Copyright (c) 2013 Vladimir Keleshev, vladimir@keleshev.com
Function Documentation
docopt()
def cppcodebasebuildscripts.docopt.docopt (doc, argv = None, help = True, version = None, options_first = False)
Parse `argv` based on command-line interface described in `doc`.
`docopt` creates your command-line interface based on its
description that you pass as `doc`. Such description can contain
--options, <positional-argument>, commands, which could be
[optional], (required), (mutually | exclusive) or repeated...
Parameters
----------
doc : str
    Description of your command-line interface.
argv : list of str, optional
    Argument vector to be parsed. sys.argv[1:] is used if not
    provided.
help : bool (default: True)
    Set to False to disable automatic help on -h or --help
    options.
version : any object
    If passed, the object will be printed if --version is in
    `argv`.
options_first : bool (default: False)
    Set to True to require options preceed positional arguments,
    i.e. to forbid options and positional arguments intermix.
Returns
-------
args : dict
    A dictionary, where keys are names of command-line elements
    such as e.g. "--verbose" and "<path>", and values are the
    parsed values of those elements.
Example
-------
>>> from docopt import docopt
>>> doc = '''
Usage:
    my_program tcp <host> <port> [--timeout=<seconds>]
    my_program serial <port> [--baud=<n>] [--timeout=<seconds>]
    my_program (-h | --help | --version)
Options:
    -h, --help  Show this screen and exit.
    --baud=<n>  Baudrate [default: 9600]
'''
>>> argv = ['tcp', '127.0.0.1', '80', '--timeout', '30']
>>> docopt(doc, argv)
{'--baud': '9600',
 '--help': False,
 '--timeout': '30',
 '--version': False,
 '<host>': '127.0.0.1',
 '<port>': '80',
 'serial': False,
 'tcp': True}
See also
--------
* For video introduction see http://docopt.org
* Full documentation is available in README.rst as well as online
  at https://github.com/docopt/docopt#readme
References cppcodebasebuildscripts.docopt.extras(), cppcodebasebuildscripts.docopt.formal_usage(), cppcodebasebuildscripts.docopt.parse_argv(), cppcodebasebuildscripts.docopt.parse_defaults(), cppcodebasebuildscripts.docopt.parse_pattern(), and cppcodebasebuildscripts.docopt.printable_usage().
extras()
def cppcodebasebuildscripts.docopt.extras (help, version, options, doc)
Referenced by cppcodebasebuildscripts.docopt.docopt().
formal_usage()
def cppcodebasebuildscripts.docopt.formal_usage (printable_usage)
Referenced by cppcodebasebuildscripts.docopt.docopt().
parse_argv()
def cppcodebasebuildscripts.docopt.parse_argv (tokens, options, options_first = False)
Parse command-line argument vector.
If options_first:
    argv ::= [ long | shorts ]* [ argument ]* [ '--' [ argument ]* ] ;
else:
    argv ::= [ long | shorts | argument ]* [ '--' [ argument ]* ] ;
References cppcodebasebuildscripts.docopt.parse_long(), and cppcodebasebuildscripts.docopt.parse_shorts().
Referenced by cppcodebasebuildscripts.docopt.docopt().
parse_atom()
def cppcodebasebuildscripts.docopt.parse_atom (tokens, options)
atom ::= '(' expr ')' | '[' expr ']' | 'options'
         | long | shorts | argument | command ;
References cppcodebasebuildscripts.docopt.parse_expr(), cppcodebasebuildscripts.docopt.parse_long(), and cppcodebasebuildscripts.docopt.parse_shorts().
Referenced by cppcodebasebuildscripts.docopt.parse_seq().
parse_defaults()
def cppcodebasebuildscripts.docopt.parse_defaults (doc)
Referenced by cppcodebasebuildscripts.docopt.docopt().
parse_expr()
def cppcodebasebuildscripts.docopt.parse_expr (tokens, options)
expr ::= seq ('|' seq)* ;
References cppcodebasebuildscripts.docopt.parse_seq().
Referenced by cppcodebasebuildscripts.docopt.parse_atom(), and cppcodebasebuildscripts.docopt.parse_pattern().
parse_long()
def cppcodebasebuildscripts.docopt.parse_long (tokens, options)
long ::= '--' chars [ (' ' | '=') chars ] ;
Referenced by cppcodebasebuildscripts.docopt.parse_argv(), and cppcodebasebuildscripts.docopt.parse_atom().
parse_pattern()
def cppcodebasebuildscripts.docopt.parse_pattern (source, options)
References cppcodebasebuildscripts.docopt.parse_expr().
Referenced by cppcodebasebuildscripts.docopt.docopt().
parse_seq()
def cppcodebasebuildscripts.docopt.parse_seq (tokens, options)
seq ::= (atom [ '...' ])* ;
References cppcodebasebuildscripts.docopt.parse_atom().
Referenced by cppcodebasebuildscripts.docopt.parse_expr().
parse_shorts()
def cppcodebasebuildscripts.docopt.parse_shorts (tokens, options)
shorts ::= '-' (chars)* [ [ ' ' ] chars ] ;
Referenced by cppcodebasebuildscripts.docopt.parse_argv(), and cppcodebasebuildscripts.docopt.parse_atom().
printable_usage()
def cppcodebasebuildscripts.docopt.printable_usage (doc)
Referenced by cppcodebasebuildscripts.docopt.docopt().