MyCPFProject: CPFJenkinsjob.setup Namespace Reference
CPFJenkinsjob.setup Namespace Reference
Functions
def main (config_file)
def get_job_name (job_base_name)
def configure_job_config_file (xml_file_path, job_name, build_repository_address, jenkinsjob_repository_address)
Detailed Description
This script runs the CPFMachines setupdDockerContainer.py script,
but adds additional CPFJenkinsjob jobs.
The script takes a .json config file for the machine setup, which can
contain an additional dictionary for defineing CMakeProjectFramework jobs.
{
  ...
  "CMakeProjectFrameworkJobs" : {
"MyCPFProjectJob" : "ssh://me@repository_machine:/share/MyRepo.git"
  },
  ...
}
Function Documentation
configure_job_config_file()
def CPFJenkinsjob.setup.configure_job_config_file (xml_file_path, job_name, build_repository_address, jenkinsjob_repository_address)
Fills in the blanks in the config file and copies it to the given job
directory.
References CPFJenkinsjob.setup.main().
Referenced by CPFJenkinsjob.setup.main().
get_job_name()
def CPFJenkinsjob.setup.get_job_name (job_base_name)
Add the version to the base name.
Referenced by CPFJenkinsjob.setup.main().
main()
def CPFJenkinsjob.setup.main (config_file)
References CPFJenkinsjob.setup.configure_job_config_file(), and CPFJenkinsjob.setup.get_job_name().
Referenced by CPFJenkinsjob.setup.configure_job_config_file().