documentation: Sources/APackage/function.h File Reference
function.h File Reference
#include <APackage/a_export.h>
Functions
A_EXPORT int mainImpl (int argc, char **argv)
Function Documentation
mainImpl()
A_EXPORT int mainImpl (int argc, char ** argv)
References e::function(), c::function(), d::function(), and d::function2().
Referenced by main().