// This file is generated by CPFCMake.
// It contains the version number of the package .

#include <string>

namespace c
{
	inline const std::string& getPackageVersion()
	{
		static std::string version = "1.1.6.62-0982";
		return version;
	}
}
