// This file is generated by CPFCMake.
// It contains the version number of the package .

#include <string>

namespace swo
{
	inline const std::string& getPackageVersion()
	{
		static std::string version = "0.0.0.24-43b2";
		return version;
	}
}
