CMakeProjectFramework: CPFMachines.fileutil Namespace Reference
CPFMachines.fileutil Namespace Reference
Functions
def clear_rdirectory (sftp_client, directory)
def rexists (sftp_client, path)
def rrmtree (sftp_client, dir_path)
def rmakedirs (sftp_client, dir_path)
def guarantee_directory_exists (sftp_client, dir_path)
def copy_local_files_to_host (connection, source_dir, context_dir, text_files, binary_files=[])
def copy_textfile_from_local_to_linux (connection, source_path, target_path)
def copy_file_from_local_to_remote (sftp_client, source_path, target_path)
def rtorcopy (source_sftp_client, target_sftp_client, source_file, target_file)
def get_dir_content (directory)
def clear_dir (directory)
def make_remote_file_executable (connection, file)
Detailed Description
Contains functions for fileoperations between the local machine, host machines and docker containers.
Function Documentation
clear_dir()
def CPFMachines.fileutil.clear_dir (directory)
After calling this function the directory will exist and be empty.
clear_rdirectory()
def CPFMachines.fileutil.clear_rdirectory (sftp_client, directory)
This functions deletes the given directory and all its content and recreates it.
It does it on the given machine.
References CPFMachines.fileutil.rexists(), CPFMachines.fileutil.rmakedirs(), and CPFMachines.fileutil.rrmtree().
copy_file_from_local_to_remote()
def CPFMachines.fileutil.copy_file_from_local_to_remote (sftp_client, source_path, target_path)
Copies a file to a host machine defined by connection, without changing it.
References CPFMachines.fileutil.rmakedirs().
Referenced by CPFMachines.fileutil.copy_local_files_to_host(), and CPFMachines.fileutil.copy_textfile_from_local_to_linux().
copy_local_files_to_host()
def CPFMachines.fileutil.copy_local_files_to_host (connection, source_dir, context_dir, text_files, binary_files = [])
context_dir is the directory on the host that is used as a build context for the container.
source_dir is the absolute directory on the machine executing the script that contains the files
required for building the container.
References CPFMachines.fileutil.copy_file_from_local_to_remote(), and CPFMachines.fileutil.copy_textfile_from_local_to_linux().
copy_textfile_from_local_to_linux()
def CPFMachines.fileutil.copy_textfile_from_local_to_linux (connection, source_path, target_path)
This function ensures that the file-endings of the text-file are set to linux
convention after the copy.
References CPFMachines.fileutil.copy_file_from_local_to_remote().
Referenced by CPFMachines.fileutil.copy_local_files_to_host().
get_dir_content()
def CPFMachines.fileutil.get_dir_content (directory)
Returns a list of all files and directories in a directory with pathes relative to the given directory.
guarantee_directory_exists()
def CPFMachines.fileutil.guarantee_directory_exists (sftp_client, dir_path)
References CPFMachines.fileutil.rexists(), and CPFMachines.fileutil.rmakedirs().
make_remote_file_executable()
def CPFMachines.fileutil.make_remote_file_executable (connection, file)
rexists()
def CPFMachines.fileutil.rexists (sftp_client, path)
Returns true if the remote directory or file under path exists.
Referenced by CPFMachines.fileutil.clear_rdirectory(), CPFMachines.fileutil.guarantee_directory_exists(), and CPFMachines.fileutil.rmakedirs().
rmakedirs()
def CPFMachines.fileutil.rmakedirs (sftp_client, dir_path)
Creates a remote directory and all its parent directories.
References CPFMachines.fileutil.rexists().
Referenced by CPFMachines.fileutil.clear_rdirectory(), CPFMachines.fileutil.copy_file_from_local_to_remote(), and CPFMachines.fileutil.guarantee_directory_exists().
rrmtree()
def CPFMachines.fileutil.rrmtree (sftp_client, dir_path)
Removes the remote directory and its content.
Referenced by CPFMachines.fileutil.clear_rdirectory().
rtorcopy()
def CPFMachines.fileutil.rtorcopy (source_sftp_client, target_sftp_client, source_file, target_file)
Copy a file from one remote machine to another.